#!/usr/bin/env python3
"""
Generate components/ui/CategoryIcons.tsx from the six category glyphs in
the Figma file (the tiles in "Frame 10").

These are separate from the 27 unique page icons: they live inside
instance nodes on the category cards and are not reachable from the
generic vector sweep in figma_assets.py, because they are component
instances rather than loose VECTOR nodes.

The file JSON has to be fetched with geometry=paths - the plain /files
response omits vector paths entirely.

Run:  python scripts/gen_category_icons.py
"""

import json
import os
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
OUT = os.path.join(ROOT, "components", "ui", "CategoryIcons.tsx")
CACHE = os.path.join(ROOT, ".figma", "cat_nodes.json")

FILE_KEY = os.environ.get("FIGMA_FILE_KEY", "OfiTDVmxnfjhcKcdLVtk0A")
TOKEN = os.environ["FIGMA_TOKEN"]

# node id -> exported name
ICONS = [
    ("11:71", "design"),
    ("12:157", "development"),
    ("12:159", "itSoftware"),
    ("12:166", "business"),
    ("12:162", "marketing"),
    ("12:164", "photography"),
]

HEADER = '''// AUTO-GENERATED by scripts/gen_category_icons.py - do not edit by hand.
// Source: the six category glyphs in the Figma home frame.

import type { SVGProps } from "react";

type Glyph = { viewBox: string; body: string };

const GLYPHS: Record<Name, Glyph> = {
'''

FOOTER = '''};

export const CATEGORY_ICON_NAMES = [
  "design",
  "development",
  "itSoftware",
  "business",
  "marketing",
  "photography",
] as const;

export type CategoryIconName = (typeof CATEGORY_ICON_NAMES)[number];
type Name = CategoryIconName;

type IconProps = Omit<SVGProps<SVGSVGElement>, "name"> & {
  name: CategoryIconName;
  size?: number;
};

/**
 * The category glyphs inherit colour from the surrounding text via
 * currentColor, so `className="text-ink"` tints them.
 */
export function CategoryIcon({ name, size = 36, className, ...rest }: IconProps) {
  const { viewBox, body } = GLYPHS[name];
  return (
    <svg
      width={size}
      height={size}
      viewBox={viewBox}
      fill="currentColor"
      aria-hidden="true"
      focusable="false"
      className={className}
      dangerouslySetInnerHTML={{ __html: body }}
      {...rest}
    />
  );
}
'''


def fetch():
    url = (
        "https://api.figma.com/v1/files/%s/nodes?ids=%s&geometry=paths&depth=4"
        % (FILE_KEY, ",".join(i for i, _ in ICONS))
    )
    req = urllib.request.Request(url, headers={"X-Figma-Token": TOKEN})
    with urllib.request.urlopen(req) as r:
        data = json.load(r)
    with open(CACHE, "w", encoding="utf-8") as fh:
        json.dump(data, fh)
    return data


def geometry_of(node):
    """Flatten a node's vector geometry into SVG path elements."""
    parts = []
    for child in node.get("children", []) or []:
        paths = child.get("fillGeometry") or child.get("pathGeometry") or []
        for p in paths:
            if p.get("path"):
                parts.append('<path d="%s"/>' % p["path"])
        if child.get("strokeGeometry") and child.get("strokeWeight"):
            w = child["strokeWeight"]
            for p in child["strokeGeometry"]:
                if p.get("path"):
                    parts.append(
                        '<path d="%s" fill="none" stroke="currentColor" '
                        'stroke-width="%s" stroke-linecap="round" '
                        'stroke-linejoin="round"/>' % (p["path"], w)
                    )
        parts.extend(geometry_of(child))
    return parts


def main():
    data = fetch() if not os.path.exists(CACHE) else json.load(
        open(CACHE, encoding="utf-8")
    )
    nodes = data["nodes"]

    lines = []
    for node_id, name in ICONS:
        node = nodes[node_id]["document"]
        box = node.get("absoluteBoundingBox") or {}
        w = box.get("width", 36) or 36
        h = box.get("height", 36) or 36
        body = "".join(geometry_of(node))
        if not body:
            raise SystemExit("no geometry for %s (%s)" % (name, node_id))
        lines.append(
            '  %s: { viewBox: "0 0 %g %g", body: %s },'
            % (name, w, h, json.dumps(body))
        )

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(HEADER + "\n".join(lines) + "\n" + FOOTER)
    print("wrote %s with %d icons" % (OUT, len(lines)))


if __name__ == "__main__":
    main()
