#!/usr/bin/env python3
"""
Generate components/ui/icons.tsx from the exported SVGs in public/assets/icons.

External `<use href="...svg">` references are blocked by browsers, so the
glyphs have to be inlined. Hardcoded fills are normalised to currentColor so
each icon can take its colour from the surrounding text (the design uses
text colour to tone icons, e.g. a lime star on a blue hero).

Run:  python scripts/gen_icons.py
"""

import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "public", "assets", "icons")
OUT = os.path.join(HERE, "..", "components", "ui", "icons.tsx")

HEADER = '''// AUTO-GENERATED by scripts/gen_icons.py - do not edit by hand.
// Source: the 27 unique glyph vectors in the ByteSpace Figma file.

import type { SVGProps } from "react";

const P = {
'''

FOOTER = '''};

export const ICON_NAMES = Object.keys(P) as IconNameArray;
export type IconName = keyof typeof P;
type IconNameArray = readonly IconName[];

type IconProps = Omit<SVGProps<SVGSVGElement>, "name"> & {
  name: IconName;
  /** Design sizes are 12 / 16 / 20 / 24 / 32 / 40 / 60. */
  size?: number;
};

/**
 * Every glyph inherits colour from the surrounding text via currentColor, so
 * `className="text-lime"` tints the icon.
 */
export function Icon({ name, size = 20, className, ...rest }: IconProps) {
  const { viewBox, body } = P[name];
  return (
    <svg
      width={size}
      height={size}
      viewBox={viewBox}
      fill="currentColor"
      aria-hidden="true"
      focusable="false"
      className={className}
      {...rest}
    >
      {body}
    </svg>
  );
}
'''


def clean(raw):
    """Strip the svg wrapper attrs and normalise fills to currentColor."""
    m = re.search(r'viewBox="([^"]+)"', raw)
    view_box = m.group(1) if m else "0 0 20 20"
    inner = re.sub(r"^.*?<svg[^>]*>", "", raw, flags=re.S)
    inner = re.sub(r"</svg>\s*$", "", inner, flags=re.S)
    inner = re.sub(r'fill="(?!none)[^"]*"', 'fill="currentColor"', inner)
    inner = re.sub(r"\s+", " ", inner).strip()
    return view_box, inner


def main():
    names = sorted(f for f in os.listdir(SRC) if f.endswith(".svg"))
    parts = []
    for name in names:
        stem = name[:-4]
        with open(os.path.join(SRC, name), encoding="utf-8") as fh:
            view_box, body = clean(fh.read())
        parts.append('  "%s": { viewBox: "%s", body: <%s /> },' % (stem, view_box, body))

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(HEADER + "\n".join(parts) + "\n" + FOOTER)
    print("wrote %s with %d icons" % (OUT, len(names)))


if __name__ == "__main__":
    main()
